[versions]
agp = "8.13.2"
kotlin = "2.3.0"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
sha2 = { module = "org.kotlincrypto.hash:sha2", version = "0.8.0" }
crypto-rand = { module = "org.kotlincrypto.random:crypto-rand", version = "0.6.0" }

[plugins]
androidLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
vanniktech-mavenPublish = { id = "com.vanniktech.maven.publish", version = "0.35.0" }
